name: Deploy Frontend

on:
  push:
    branches:
      - main  # 或者是你用于部署的分支
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 选择适合你项目的Node.js版本

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "dist/*"  # 根据你的构建输出目录调整这里
          target: "/root/www/bridge-app/dist"  # 你的项目部署目录

